name: SimpleJumpPads
version: '${version}'
author: 4drian3d
main: io.github._4drian3d.simplejumppads.SimpleJumpPads
bootstrapper: io.github._4drian3d.simplejumppads.JumpPadsBootstrap
description: Simple JumPads for Paper
api-version: '1.21'
folia-supported: true